

[[redirects]]
  from = "/about-me"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/about-us"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/contact-me"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/contact-us"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404